# Generated by Django 4.2.6 on 2023-10-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_done',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=155, verbose_name='Title'),
        ),
    ]
